name: Bitski Internal SDK
on:
  pull_request:
    paths:
      - .github/workflows/bitski-internal-sdk.yaml
      - .github/workflows/docker.yaml
      - docker-compose.yaml
      - Dockerfile
  push:
    branches: [main]
  schedule:
    - cron: "16 0 * * 0"

jobs:
  openshift:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: openshift-${{ github.sha }}
      tags: latest
      target: openshift-builder
      push: false
      save_artifact: openshift
      cache_tag: openshift
      matrix: |
        {"tags": "openshift"}
      dockle: false
      trivy: false

  cargo-cache:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-cache-${{ github.sha }}
      tags: latest
      target: cargo-cache-builder
      push: false
      save_artifact: cargo-cache
      cache_tag: cargo-cache
      matrix: |
        {"tags": "cargo-cache"}
      dockle: false
      trivy: false

  cargo-edit:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-edit-${{ github.sha }}
      tags: latest
      target: cargo-edit-builder
      push: false
      save_artifact: cargo-edit
      cache_tag: cargo-edit
      matrix: |
        {"tags": "cargo-edit"}
      dockle: false
      trivy: false

  cargo-udeps:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-udeps-${{ github.sha }}
      tags: latest
      target: cargo-udeps-builder
      push: false
      save_artifact: cargo-udeps
      cache_tag: cargo-udeps
      matrix: |
        {"tags": "cargo-udeps"}
      dockle: false
      trivy: false

  diesel:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: diesel-${{ github.sha }}
      tags: latest
      target: diesel-builder
      push: false
      save_artifact: diesel
      cache_tag: diesel
      matrix: |
        {"tags": "diesel"}
      dockle: false
      trivy: false

  download:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: download-${{ github.sha }}
      tags: latest
      target: download-builder
      push: false
      save_artifact: download
      cache_tag: download
      matrix: |
        {"tags": "download"}
      dockle: false
      trivy: false

  devcontainer:
    name: Devcontainer
    needs:
      - openshift
      - cargo-cache
      - cargo-edit
      - cargo-udeps
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: devcontainer
      target: devcontainer
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        CARGO_EDIT_BIN_BASE=localhost:5000/cargo-edit-${{ github.sha }}
        CARGO_UDEPS_BIN_BASE=localhost:5000/cargo-udeps-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=latest,nightly
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        cargo-edit
        cargo-udeps
        diesel
        download
      cache_tag: devcontainer
      startup_test: true
      startup_image_env_name: DEVCONTAINER_IMAGE
      matrix: |
        {"tags": "devcontainer"}
      dockle: false
      trivy: false

  rust-1-59:
    name: Rust 1.59
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: |
        rust
        rust-1.59
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=1.59
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache_tag: rust-1.59
      matrix: |
        {"tags": "rust-1.59"}

  rust-1-58:
    name: Rust 1.58
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.58
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=1.58
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache_tag: rust-1.58
      matrix: |
        {"tags": "rust-1.58"}

  rust-1-57:
    name: Rust 1.57
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.57
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=1.57
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache_tag: rust-1.57
      matrix: |
        {"tags": "rust-1.57"}

  rust-1-56:
    name: Rust 1.56
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.56
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=1.56
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache_tag: rust-1.56
      matrix: |
        {"tags": "rust-1.56"}

  rust-1-55:
    name: Rust 1.55
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.55
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=1.55
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache_tag: rust-1.55
      matrix: |
        {"tags": "rust-1.55"}
