name: Bitski Internal SDK
on:
  pull_request:
    paths:
      - .github/workflows/bitski-internal-sdk.yaml
      - .github/workflows/docker.yaml
      - docker-compose.yaml
      - Dockerfile
  push:
    branches: [main]
  schedule:
    - cron: "16 0 * * 0"

jobs:
  cargo:
    name: Cargo
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-${{ github.sha }}
      tags: latest
      target: cargo
      push: false
      save_artifact: cargo
      cache_tag: cargo
      matrix: |
        {"tags": "cargo"}
      dockle: false
      trivy: false

  devcontainer:
    name: Devcontainer
    needs: cargo
    uses: ./.github/workflows/docker.yaml
    with:
      tags: devcontainer
      target: devcontainer
      build_args: |
        CARGO_BIN_BASE=localhost:5000/cargo-${{ github.sha }}
        USERNAME=bitski
        RUST_VERSION=latest,nightly
      archs: |
        amd64
        arm64
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: cargo
      cache_tag: devcontainer
      startup_test: true
      startup_image_env_name: DEVCONTAINER_IMAGE
      matrix: |
        {"tags": "devcontainer"}
      dockle: false

  rust_1_58:
    name: Rust 1.58
    needs: cargo
    uses: ./.github/workflows/docker.yaml
    with:
      tags: |
        rust
        rust-1.58
      target: rust
      build_args: |
        CARGO_BIN_BASE=localhost:5000/cargo-${{ github.sha }}
        RUST_VERSION=1.58,nightly
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: cargo
      cache_tag: rust-1.58
      matrix: |
        {"tags": "rust-1.58"}
      dockle: false

  rust_1_57:
    name: Rust 1.57
    needs: cargo
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.57
      target: rust
      build_args: |
        CARGO_BIN_BASE=localhost:5000/cargo-${{ github.sha }}
        RUST_VERSION=1.57,nightly
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: cargo
      cache_tag: rust-1.57
      matrix: |
        {"tags": "rust-1.57"}
      dockle: false

  rust_1_56:
    name: Rust 1.56
    needs: cargo
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.56
      target: rust
      build_args: |
        CARGO_BIN_BASE=localhost:5000/cargo-${{ github.sha }}
        RUST_VERSION=1.56
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: cargo
      cache_tag: rust-1.56
      matrix: |
        {"tags": "rust-1.56"}
      dockle: false

  rust_1_55:
    name: Rust 1.55
    needs: cargo
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust-1.55
      target: rust
      build_args: |
        CARGO_BIN_BASE=localhost:5000/cargo-${{ github.sha }}
        RUST_VERSION=1.55
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: cargo
      cache_tag: rust-1.55
      matrix: |
        {"tags": "rust-1.55"}
      dockle: false
