name: Bitski Internal SDK

on:
  pull_request:
    paths:
      - .github/workflows/bitski-internal-sdk.yaml
      - .github/workflows/docker.yaml
      - docker-compose.yaml
      - Dockerfile
  push:
    branches: [main]
  schedule:
    # Release Sundays at 4:16 PM PST
    - cron: "16 0 * * 0"

concurrency: 
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  openshift:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: openshift-${{ github.sha }}
      tags: latest
      target: openshift-builder
      push: false
      save_artifact: openshift
      cache: true
      cache_tag: openshift
      matrix: |
        {"tags": "openshift"}
      dockle: false
      trivy: false

  cargo-cache:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-cache-${{ github.sha }}
      tags: latest
      target: cargo-cache-builder
      push: false
      save_artifact: cargo-cache
      cache: true
      cache_tag: cargo-cache
      matrix: |
        {"tags": "cargo-cache"}
      dockle: false
      trivy: false

  cargo-edit:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-edit-${{ github.sha }}
      tags: latest
      target: cargo-edit-builder
      push: false
      save_artifact: cargo-edit
      cache: true
      cache_tag: cargo-edit
      matrix: |
        {"tags": "cargo-edit"}
      dockle: false
      trivy: false

  cargo-udeps:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: cargo-udeps-${{ github.sha }}
      tags: latest
      target: cargo-udeps-builder
      push: false
      save_artifact: cargo-udeps
      cache: true
      cache_tag: cargo-udeps
      matrix: |
        {"tags": "cargo-udeps"}
      dockle: false
      trivy: false

  diesel:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: diesel-${{ github.sha }}
      tags: latest
      target: diesel-builder
      push: false
      save_artifact: diesel
      cache: true
      cache_tag: diesel
      matrix: |
        {"tags": "diesel"}
      dockle: false
      trivy: false

  download:
    uses: ./.github/workflows/docker.yaml
    with:
      registry: localhost:5000
      image_name: download-${{ github.sha }}
      tags: latest
      target: download-builder
      push: false
      save_artifact: download
      cache: true
      cache_tag: download
      matrix: |
        {"tags": "download"}
      dockle: false
      trivy: false

  devcontainer:
    name: Devcontainer
    needs:
      - openshift
      - cargo-cache
      - cargo-edit
      - cargo-udeps
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: devcontainer
      target: devcontainer
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        CARGO_EDIT_BIN_BASE=localhost:5000/cargo-edit-${{ github.sha }}
        CARGO_UDEPS_BIN_BASE=localhost:5000/cargo-udeps-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
        RUST_VERSION=latest,nightly
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        cargo-edit
        cargo-udeps
        diesel
        download
      cache: true
      cache_tag: devcontainer
      startup_test: true
      startup_image_env_name: DEVCONTAINER_IMAGE
      matrix: |
        {"tags": "devcontainer"}
      dockle: false
      trivy: false

  rust:
    name: Rust
    needs:
      - openshift
      - cargo-cache
      - diesel
      - download
    uses: ./.github/workflows/docker.yaml
    with:
      tags: rust
      target: rust
      build_args: |
        OPENSHIFT_BIN_BASE=localhost:5000/openshift-${{ github.sha }}
        CARGO_CACHE_BIN_BASE=localhost:5000/cargo-cache-${{ github.sha }}
        DIESEL_BIN_BASE=localhost:5000/diesel-${{ github.sha }}
        DOWNLOAD_BIN_BASE=localhost:5000/download-${{ github.sha }}
      push: ${{ github.event_name != 'pull_request' }}
      load_artifacts: |
        openshift
        cargo-cache
        diesel
        download
      cache: true
      cache_tag: rust
      matrix: |
        {"tags": "rust"}
