name: Docker

on:
  workflow_call:
    inputs:
      registry:
        description: "Docker registry"
        type: string
        default: ghcr.io
      registry_username:
        description: "Docker registry username. Default: github.actor"
        type: string
      file:
        description: "Path to Dockerfile"
        type: string
        default: Dockerfile
      context:
        description: "Path to Docker build context"
        type: string
        default: "."
      image_name:
        description: "Docker image name. Default: github.repository"
        type: string
      target:
        description: "Target stage to build"
        type: string
      build_args:
        description: "Docker build args"
        type: string
      tags:
        description: "Docker tags"
        type: string
        default: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha,format=long
      archs:
        description: >-
          Architectures to include in multi-arch manifest. Only the native
          architecture image will be built as `<image-name>-<arch>`, e.g.
          `devcontainer-amd64`. Other platform images must exist in the
          registry as `<image-name>-<arch>`. The multi-arch build will include
          the latest `<image-name>-<arch>` images in the multi-arch manifest.
        type: string
      push:
        description: "If true, push the build to the registry"
        type: boolean
        default: true
      startup_test:
        description: "Run startup test with docker-compose"
        type: boolean
      startup_compose_file:
        description: "Path to docker-compose.yaml file to use for startup test"
        type: string
        default: docker-compose.yaml
      startup_image_env_name:
        description: "Environment variables to set as the built image name"
        type: string
      submodules:
        description: "Checkout submodules"
        type: string
    secrets:
      registry_password:
        description: "Docker registry password, defaults to GITHUB_TOKEN"

jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TAGS: ${{ inputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: ${{ inputs.submodules }}

      - name: Configure image tags for multiarch manifest
        if: inputs.archs
        run: |
          set -o xtrace

          ARCH=`uname -m`
          case $ARCH in
          amd64 | x86_64) 
              ARCH=amd64
              ;;
          aarch64 | arm64) 
              ARCH=arm64
              ;;
          esac

          TAGS=`echo "$TAGS" | sed "s/\$/-$ARCH/"`

          echo "TAGS=$(printf '%q' "$TAGS")" | tee -a $GITHUB_ENV

      - name: Configure SSH Agent
        if: inputs.ssh_private_keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ inputs.ssh_private_keys }}

      - name: Save Git and SSH config
        if: inputs.ssh_private_keys
        run: |
          GIT_CONFIG=`cat ~/.gitconfig`
          printf 'GIT_CONFIG=%q' "$GIT_CONFIG" | tee -a $GITHUB_ENV

          SSH_CONFIG=`cat ~/.ssh/config |
            sed 's/IdentitiesOnly yes/ForwardAgent yes/g'`
          printf 'SSH_CONFIG=%q' "$SSH_CONFIG" | tee -a $GITHUB_ENV

      - name: Configure Docker build args
        id: build_args
        env:
          SCOPE: ${{ runner.os }}-${{ runner.arch }}-docker-${{ hashFiles(inputs.file) }}
        run: |
          echo "::set-output name=cache_from::type=gha,scope=$SCOPE"
          echo "::set-output name=cache_to::type=gha,scope=${SCOPE},mode=max"

          if [[ -n "$SSH_AUTH_SOCK" ]]; then
            echo "::set-output name=ssh::default=$SSH_AUTH_SOCK"
          fi

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          driver-opts: network=host
          install: true

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name || github.repository }}
          tags: ${{ env.TAGS }}

      - name: Build Docker image
        id: docker
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.file }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build_args }}
          ssh: ${{ steps.build_args.outputs.ssh }}
          cache-from: ${{ steps.build_args.outputs.cache_from }}
          cache-to: ${{ steps.build_args.outputs.cache_to }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ inputs.target }}

      - name: Configure local image name
        id: local
        env:
          TAGS: ${{ fromJSON(steps.docker.outputs.metadata)['image.name'] }}
        run: |
          IFS=$', ' command eval 'TAGS=($TAGS)'
          echo "::set-output name=image_name::${TAGS[0]}"

      - name: Run startup tests
        if: inputs.startup_test
        env:
          FILE: ${{ inputs.startup_compose_file }}
          IMAGE_ENV_NAME: ${{ inputs.startup_image_env_name }}
          BUILT_TAG: ${{ steps.local.outputs.image_name }}
        run: |
          if [[ -n "$IMAGE_ENV_NAME" ]]; then
            eval "export ${IMAGE_ENV_NAME}=$BUILT_TAG"
          fi

          echo '::group::docker compose up'
          docker compose --file "$FILE" up --wait
          EXIT_CODE=$?
          echo '::endgroup::'

          echo '::group::docker compose logs'
          docker compose logs
          echo '::endgroup::'

          echo '::group::docker compose down'
          docker compose kill
          docker compose down
          echo '::endgroup::'

          exit $EXIT_CODE

      - name: Scan for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.local.outputs.image_name }}
          # format: sarif
          # output: trivy-results.sarif

      # TODO(jacob): Integrate Trivy with GitHub Security
      # - name: Upload Trivy scan results to the GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: trivy-results.sarif

      # TODO(jacob): Configure Dockle lint
      - name: Lint with Dockle
        env:
          IMAGE: ${{ steps.local.outputs.image_name }}
        run: |
          docker run --rm goodwithtech/dockle:latest "$IMAGE"

      - name: Log into Docker registry
        if: inputs.push
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username || github.actor }}
          password: ${{ secrets.registry_password || github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.file }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build_args }}
          ssh: ${{ steps.build_args.outputs.ssh }}
          cache-from: ${{ steps.build_args.outputs.cache_from }}
          cache-to: ${{ steps.build_args.outputs.cache_to }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ inputs.target }}

      - name: Create multiarch manifest
        if: inputs.archs
        env:
          ARCHS: ${{ inputs.archs }}
          BASE_TAGS: ${{ inputs.tags }}
          BASE_MANIFEST: ${{ inputs.registry }}/${{ inputs.image_name || github.repository }}
          BUILT_TAGS: ${{ steps.local.outputs.image_name }}
        run: |
          IFS=$'\n ' command eval 'ARCHS=($ARCHS)'
          IFS=$'\n ' command eval 'BASE_TAGS=($BASE_TAGS)'
          BASE_MANIFEST="${BASE_MANIFEST,,}"

          IFS=$'\n ' command eval 'BUILT_TAGS=($BUILT_TAGS)'
          BUILT_TAGS="^($(IFS=\|; echo "${BUILT_TAGS[*]}"))$"

          MANIFESTS=()
          for BASE_TAG in "${BASE_TAGS[@]}"; do
            MANIFEST="${BASE_MANIFEST}:${BASE_TAG}"

            AMEND=()
            for PLATFORM in "${ARCHS[@]}"; do
              IMAGE_NAME="${MANIFEST}-${PLATFORM}"
              echo "::group::docker pull $IMAGE_NAME"
              if [[ "$IMAGE_NAME" =~ $BUILT_TAGS ]]; then
                docker pull "$IMAGE_NAME"
              else
                echo "Not pulling built image $IMAGE_NAME"
              fi
              echo '::endgroup::'
              AMEND+=(--amend "$IMAGE_NAME")
            done

            echo "::group::docker manifest create"
            docker manifest create "$MANIFEST" "${AMEND[@]}"
            echo '::endgroup::'
            MANIFESTS+=("$MANIFEST")
          done

          MANIFESTS=`IFS=$'\n'; echo "${MANIFESTS[*]}"`
          echo "MANIFESTS=$(printf '%q' "$MANIFESTS")" | tee -a $GITHUB_ENV

      - name: Push multiarch manifest
        if: inputs.push && env.MANIFESTS != null
        run: echo "$MANIFESTS" | xargs -n1 docker manifest push
