name: Rollback

on:
  pull_request:
    paths:
      - .github/workflows/rollback.yaml
  workflow_call:
    inputs:
      registry:
        description: "Docker registry"
        default: ghcr.io
        type: string
      registry_username:
        description: "Docker registry username"
        default: ${{ github.actor }}
        type: string
      image_name:
        description: "Docker image name"
        # github.repository as <account>/<repo>
        default: ${{ github.repository }}
        type: string
      target_tag:
        description: "The target image tag to rollback"
        default: latest
        type: string
      rollback_tag:
        description: "The rollback image tag"
        default: rollback
        type: string
      release_workflow:
        description: "Release workflow in the same repo to disable"
        default: Release
        type: string
    secrets:
      registry_password:
        description: "Docker registry password, defaults to GITHUB_TOKEN"

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ${{ inputs.registry || 'ghcr.io' }}
    permissions:
      actions: write
      packages: write
    steps:
      - name: Disable release workflow
        if: github.event_name != 'pull_request' && inputs.release_workflow
        uses: actions/github-script@v5
        env:
          RELEASE_WORKFLOW: ${{ inputs.release_workflow }}
        with:
          script: |
            const workflowName = process.env.RELEASE_WORKFLOW;
            const options = context.repo;

            let workflow;
            for await (const response of github.paginate.iterator(
              github.rest.actions.listRepoWorkflows,
              options
            )) {
              core.debug(`response = ${JSON.stringify(response, null, "  ")}`);
              let wflow =
                response.data &&
                response.data.find((it) => it.name === workflowName);
              if (wflow) {
                workflow = wflow;
                break;
              }
            }

            if (workflow == null) {
              core.setFailed(
                `Workflow ${JSON.stringify(workflowName)} not found`
              );
            } else if (workflow.state === "active") {
              options.workflow_id = workflow.id;
              await github.rest.actions.disableWorkflow(options);
            }

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ inputs.registry_username || github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}

      - name: Configure image names
        env:
          # github.repository as <account>/<repo>
          IMAGE_NAME: ${{ inputs.image_name || github.repository }}
          # Image tags
          TARGET_TAG: ${{ inputs.target_tag || 'latest' }}
          ROLLBACK_TAG: ${{ inputs.rollback_tag || 'devcontainer' }}
        run: |
          IMAGE_NAME="${REGISTRY,,}/${IMAGE_NAME,,}"
          echo "TARGET_IMAGE=$IMAGE_NAME:$TARGET_TAG" | tee -a $GITHUB_ENV
          echo "ROLLBACK_IMAGE=$IMAGE_NAME:$ROLLBACK_TAG" | tee -a $GITHUB_ENV

      - name: Tag target image
        run: |
          set -o xtrace

          docker pull "$ROLLBACK_IMAGE"
          docker tag "$ROLLBACK_IMAGE" "$TARGET_IMAGE"

      - name: Push target image
        if: github.event_name != 'pull_request'
        run: docker push "$TARGET_IMAGE"
